version: '2.13.0'

services:
  app:
    image: ceiq-shop-next
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./backend_crypto:/app/backend_crypto
      - ./components:/app/components
      - ./contracts:/app/contracts
      - ./migrations:/app/migrations
      - ./models:/app/models
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./utils:/app/utils
