// export const data = {
//   PayboxRemail: 'drfernandotorresjaramillo@hotmail.com',
//   PayboxSendmail: 'user_ema@doain.com',
//   PayboxRename: 'Pago Plux Establecimiento',
//   PayboxSendname: 'Nombre Cliente',
//   PayboxBase0: '2.7',
//   PayboxBase12: '8',
//   PayboxDescription: 'Pago Testa',
//   PayboxLanguage: 'es',
//   PayboxRequired: [],
//   PayboxDirection: 'Bolivar 2-80 y borrero',
//   PayBoxClientPhone: '0987654321',
//   PayboxProduction: false,
//   PayBoxClientName: 'Cristian Bastidas',
//   PayBoxClientIdentification: '10030',
//   PayboxEnvironment: 'sandbox',
//   PayboxPagoPlux: true,
//   PayboxIdElement: 'idElementoTest',
// };
