const data = {
  products: [
    {
      name: 'CEIQ Surgical Skin 1.0',
      slug: 'surgical-skin-v1',
      category: 'Skins',
      image: '/images/surgical-skin-1.jpg',
      price: 15,
      countInStock: 20,
      brand: 'CEIQ',
      rating: 3.0,
      numReviews: 10,
      description: 'Piel sintética docente',
      code: '001',
    },
    {
      name: 'CEIQ Surgical Skin 2.0',
      slug: 'surgical-skin-v2',
      category: 'Skins',
      image: '/images/surgical-skin-2.jpg',
      price: 15,
      countInStock: 230,
      brand: 'CEIQ',
      rating: 5.0,
      numReviews: 30,
      description: 'Piel sintética renovada',
      code: '002',
    },
    {
      name: 'Soporte para Piel Sintética',
      slug: 'soporte-para-piel-sintetica',
      category: 'Accesorios',
      image: '/images/soporte-piel-sintetica.jpg',
      price: 15,
      countInStock: 230,
      brand: 'CEIQ',
      rating: 5.0,
      numReviews: 30,
      description:
        'Fijación y soporte a nuestra piel sintética para desarrollar un mejor trabajo en la mesa de destrezas.',
      code: '003',
    },
    {
      name: 'CEIQ Surgical Skin 1.0 MINI',
      slug: 'ceiq-surgical-skin-1-mini',
      category: 'Skins',
      image: '/images/surgical-skin-1-mini.jpg',
      price: 5,
      countInStock: 130,
      brand: 'CEIQ',
      rating: 4.8,
      numReviews: 25,
      description: 'Piel sintética docente en su versión pequeña',
      code: '004',
    },
    {
      name: 'CEIQ  Simulador para inyección intramuscular',
      slug: 'ceiq-simulador-para-inyeccion-intramuscular',
      category: 'Skins',
      image: '/images/simulador-inyeccion-intramuscular.jpg',
      price: 20,
      brand: 'CEIQ',
      countInStock: 200,
      rating: 4.5,
      numReviews: 13,
      description:
        'simulador para la aplicación de inyecciones intramusculares simuladas.',
      code: '005',
    },
    {
      name: 'Simulador Diafragmático',
      slug: 'simulador-diafragmatico',
      category: 'Endo Training',
      image: '/images/simulador-diafragmatico.jpg',
      price: 15,
      countInStock: 45,
      brand: 'CEIQ',
      rating: 4.6,
      numReviews: 20,
      description:
        'Simula la reparación de una Hernia Hiatal Laparoscópica y abierta.',
      code: '006',
    },
    {
      name: 'Endrotrainer Laparoscópico tablet 1',
      slug: 'endrotrainer-laparospo-tablet-1',
      category: 'Endo Training',
      image: '/images/endrotrainer-laparospo-tablet-1.jpg',
      price: 15,
      countInStock: 45,
      brand: 'CEIQ',
      rating: 4.6,
      numReviews: 20,
      description:
        'Sistema de entrenamiento laparoscópico portátil para que desarrolles tus destrezas desde básicas como avanzadas.',
      code: '007',
    },
    {
      name: 'Endrotrainer Laparoscópico tablet 2',
      slug: 'endrotrainer-laparospo-tablet-2',
      category: 'Endo Training',
      image: '/images/endrotrainer-laparospo-tablet-2.jpg',
      price: 15,
      countInStock: 45,
      brand: 'CEIQ',
      rating: 4.6,
      numReviews: 20,
      description:
        'Sistema de entrenamiento laparoscópico Mejorado portátil para que desarrolles tus destrezas desde básicas como avanzadas.',
      code: '008',
    },
  ],
};

export default data;
