const data = {
  products: [
    {
      name: 'CEIQ Surgical Skin 1.0',
      slug: 'surgical-skin-v1',
      category: 'Skins',
      image: '/images/skin1.jpg',
      price: 15,
      countInStock: 20,
      brand: 'CEIQ',
      rating: 3.0,
      numReviews: 10,
      description: 'Piel sintética docente',
    },
    {
      name: 'Juego Lap Aro',
      slug: 'juego-lap-aro',
      category: 'Endo Training',
      image: '/images/juegoLap.jpg',
      price: 5,
      countInStock: 10,
      brand: 'CEIQ',
      rating: 4.0,
      numReviews: 14,
      description: 'Entrenador Laparoscópico CEIQ',
    },
    {
      name: 'Kit de Sutura CEIQ',
      slug: 'kit-de-sutura-ceiq',
      category: 'Kits',
      image: '/images/kitSutura.jpg',
      price: 70,
      countInStock: 25,
      brand: 'CEIQ',
      rating: 4.8,
      numReviews: 17,
      description:
        'equipo ideal para tus primeros pasos en la realización de sutura y nudos quirúrgicos.',
    },
    {
      name: 'Simulador Diafragmático',
      slug: 'simulador-diafragmatico',
      category: 'Endo Training',
      image: '/images/diafrag.jpg',
      price: 15,
      countInStock: 45,
      brand: 'CEIQ',
      rating: 4.6,
      numReviews: 20,
      description:
        'Simula la reparación de una Hernia Hiatal Laparoscópica y abierta.',
    },
    {
      name: 'CEIQ  Simulador para inyección intramuscular',
      slug: 'ceiq-simulador-para-inyeccion-intramuscular',
      category: 'Skins',
      image: '/images/inyIntra.jpg',
      price: 20,
      brand: 'CEIQ',
      countInStock: 200,
      rating: 4.5,
      numReviews: 13,
      description:
        'simulador para la aplicación de inyecciones intramusculares simuladas.',
    },
    {
      name: 'CEIQ Surgical Skin 1.0 MINI',
      slug: 'ceiq-surgical-skin-1-mini',
      category: 'Skins',
      image: '/images/skin1Mini.jpg',
      price: 5,
      countInStock: 130,
      brand: 'CEIQ',
      rating: 4.8,
      numReviews: 25,
      description: 'Piel sintética docente en su versión pequeña',
    },
  ],
};

export default data;
